name: Fibonacci Sequence Calculation

# Trigger the action on a push to main or manually using workflow_dispatch
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  fibonacci-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Calculate Fibonacci Sequence
        run: |
          echo "Calculating the first 1000 terms of the Fibonacci sequence..."
          python3 -c "
a, b = 0, 1
with open('fibonacci_output.txt', 'w') as f:
    for i in range(1000):
        f.write(f'Fib {i+1}: {a}\n')
        a, b = b, a + b
          "
        shell: bash

      - name: Upload Fibonacci Output
        uses: actions/upload-artifact@v3
        with:
          name: fibonacci-output
          path: fibonacci_output.txt
