name: Generate SBOM for Superset Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sbom-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate SBOM for Superset Docker Image
        run: |
          echo "Generating SBOM for Apache Superset Docker image..."
          docker pull apache/superset:latest

          # Install Syft (SBOM tool) globally
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sudo sh

          # Generate SBOM using Syft
          syft docker:apache/superset:latest -o json > sbom.json

      - name: Upload SBOM Artifact
        uses: actions/upload-artifact@v3
        with:
          name: sbom-superset
          path: sbom.json
