name: Fibonacci Sequence Calculation

# Trigger the action on a push to main or manually using workflow_dispatch
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  fibonacci-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Calculate Fibonacci Sequence
        run: |
          echo "Calculating the first 1000 terms of the Fibonacci sequence..."
          python -c "
          def fibonacci(n):
              sequence = [0, 1]
              while len(sequence) < n:
                  sequence.append(sequence[-1] + sequence[-2])
              return sequence

          output = fibonacci(1000)
          with open('fibonacci_output.txt', 'w') as f:
              for num in output:
                  f.write(f'{num}\n')
          "
        shell: bash

      - name: Upload Fibonacci Output
        uses: actions/upload-artifact@v3
        with:
          name: fibonacci-output
          path: fibonacci_output.txt
